In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import ipaddress

In [5]:
import socket

In [6]:
df= pd.read_csv('/Users/sushil/Downloads/dataset_phishing.csv')

In [7]:
df

,url,length_url,length_hostname,ip,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,...,domain_in_title,domain_with_copyright,whois_registered_domain,domain_registration_length,domain_age,web_traffic,dns_record,google_index,page_rank,status
0,http://www.crestonwood.com/router.php,37,19,0,3,0,0,0,0,0,...,0,1,0,45,-1,0,1,1,4,legitimate
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1,1,0,0,0,0,0,...,1,0,0,77,5767,0,0,1,2,phishing
2,https://support-appleld.com.secureupdate.duila...,126,50,1,4,1,0,1,2,0,...,1,0,0,14,4004,5828815,0,1,0,phishing
3,http://rgipt.ac.in,18,11,0,2,0,0,0,0,0,...,1,0,0,62,-1,107721,0,0,3,legitimate
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15,0,2,2,0,0,0,0,...,0,1,0,224,8175,8725,0,0,6,legitimate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11425,http://www.fontspace.com/category/blackletter,45,17,0,2,0,0,0,0,0,...,0,0,0,448,5396,3980,0,0,6,legitimate
11426,http://www.budgetbots.com/server.php/Server%20...,84,18,0,5,0,1,1,0,0,...,1,0,0,211,6728,0,0,1,0,phishing
11427,https://www.facebook.com/Interactive-Televisio...,105,16,1,2,6,0,1,0,0,...,0,0,0,2809,8515,8,0,1,10,legitimate
11428,http://www.mypublicdomainpictures.com/,38,30,0,2,0,0,0,0,0,...,1,0,0,85,2836,2455493,0,0,4,legitimate
11429,http://174.139.46.123/ap/signin?openid.pape.ma...,477,14,1,24,0,1,1,9,0,...,1,1,1,0,-1,0,1,1,0,phishing

In [8]:
url=[]

In [9]:
for i in df['url']:
    url.append(i)

In [10]:
mydf=pd.DataFrame(url, columns=['url'])

In [11]:
def similarity(df, mydf, column):
    correct=0
    rows=len(df[column])
    for i in range(rows):
        if df[column][i]==mydf[column][i]:
            correct+=1
    print(f'Number of matching rows= {correct}')
    print(f'Similarity percentage= {correct*100/rows}')

def similarity_diff(df, mydf, column):
    correct=0
    rows=len(df[column])
    for i in range(rows):
        if abs(df[column][i]-mydf[column][i])<0.0001:
            correct+=1
    print(f'Number of matching rows= {correct}')
    print(f'Similarity percentage= {correct*100/rows}')
    
def lengthcalculator(url):
    return len(url)

def hostname(url):
    s=url.find('//')
    e=url.find('/',s+2)
    if e==-1:
        e=len(url)
    p=url.find(':',s+2)
    if p==-1:
        p=len(url)
    return(min(e,p)-s-2)

def dots(url):
    return url.count('.')
    
def hyphens(url):
    return url.count('-')

def at(url):
    return url.count('@')

def qm(url):
    return url.count('?')

def countand(url):
    return url.count('&')

def countor(url):
    return url.count('|')

def eq(url):
    return url.count('=')

def us(url):
    return url.count('_')

def tilde(url):
    return url.count('~')

def percent(url):
    return url.count('%')

def slash(url):
    return url.count('/')

def star(url):
    return url.count('*')

def colon(url):
    return url.count(':')

def comma(url):
    return url.count(',')

def semicolumn(url):
    return url.count(';')

def dollar(url):
    return url.count('$')

def space(url):
    return url.count(' ')

def www(url):
    return url.count('www')

def com(url):
    return url.count('com')

def dslash(url):
    return 1 if url.count('//')>1 else 0

def http_path(url):
    return (url.count('http')-1)

def https_tok(url):
    return 0 if url.count('https')>0 else 1

def digits(url):
    digits=0
    for i in url:
        if i.isnumeric():
            digits+=1
    return digits

def puny(url):
    return url.count('--')

def contains_port(url):
    return 1 if url.count(':')>1 else 0

def subdomains(url):
    return url.count('.')

def index(url):
    return url.find('//')

In [12]:
length_url=[]

In [13]:
for i in mydf['url']:
    length_url.append(lengthcalculator(i))

In [14]:
mydf

                                                     url
0                  http://www.crestonwood.com/router.php
1      http://shadetreetechnology.com/V4/validation/a...
2      https://support-appleld.com.secureupdate.duila...
3                                     http://rgipt.ac.in
4      http://www.iracing.com/tracks/gateway-motorspo...
...                                                  ...
11425      http://www.fontspace.com/category/blackletter
11426  http://www.budgetbots.com/server.php/Server%20...
11427  https://www.facebook.com/Interactive-Televisio...
11428             http://www.mypublicdomainpictures.com/
11429  http://174.139.46.123/ap/signin?openid.pape.ma...

[11430 rows x 1 columns]

In [15]:
mydf['length_url']=length_url

In [16]:
mydf

                                                     url  length_url
0                  http://www.crestonwood.com/router.php          37
1      http://shadetreetechnology.com/V4/validation/a...          77
2      https://support-appleld.com.secureupdate.duila...         126
3                                     http://rgipt.ac.in          18
4      http://www.iracing.com/tracks/gateway-motorspo...          55
...                                                  ...         ...
11425      http://www.fontspace.com/category/blackletter          45
11426  http://www.budgetbots.com/server.php/Server%20...          84
11427  https://www.facebook.com/Interactive-Televisio...         105
11428             http://www.mypublicdomainpictures.com/          38
11429  http://174.139.46.123/ap/signin?openid.pape.ma...         477

[11430 rows x 2 columns]

In [17]:
similarity(df, mydf, 'length_url')

Number of matching rows= 11424
Similarity percentage= 99.94750656167979

In [18]:
length_hostname=[]

In [19]:
from string import ascii_lowercase

In [20]:
for i in mydf['url']:
    length_hostname.append(hostname(i))

In [21]:
mydf['length_hostname']=length_hostname

In [22]:
mydf

,url,length_url,length_hostname
0,http://www.crestonwood.com/router.php,37,19
1,http://shadetreetechnology.com/V4/validation/a...,77,23
2,https://support-appleld.com.secureupdate.duila...,126,50
3,http://rgipt.ac.in,18,11
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15
...,...,...,...
11425,http://www.fontspace.com/category/blackletter,45,17
11426,http://www.budgetbots.com/server.php/Server%20...,84,18
11427,https://www.facebook.com/Interactive-Televisio...,105,16
11428,http://www.mypublicdomainpictures.com/,38,30
11429,http://174.139.46.123/ap/signin?openid.pape.ma...,477,14

In [23]:
similarity(df, mydf, 'length_hostname')

Number of matching rows= 11428
Similarity percentage= 99.9825021872266

In [24]:
nb_dots=[]

In [25]:
for i in mydf['url']:
    nb_dots.append(dots(i))

In [26]:
mydf['nb_dots']=nb_dots

In [27]:
similarity(df, mydf, 'nb_dots')

Number of matching rows= 11429
Similarity percentage= 99.9912510936133

In [28]:
mydf

,url,length_url,length_hostname,nb_dots
0,http://www.crestonwood.com/router.php,37,19,3
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1
2,https://support-appleld.com.secureupdate.duila...,126,50,4
3,http://rgipt.ac.in,18,11,2
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15,2
...,...,...,...,...
11425,http://www.fontspace.com/category/blackletter,45,17,2
11426,http://www.budgetbots.com/server.php/Server%20...,84,18,5
11427,https://www.facebook.com/Interactive-Televisio...,105,16,2
11428,http://www.mypublicdomainpictures.com/,38,30,2
11429,http://174.139.46.123/ap/signin?openid.pape.ma...,477,14,24

In [29]:
nb_hyphens=[]
for i in mydf['url']:
    nb_hyphens.append(hyphens(i))
mydf['nb_hyphens']=nb_hyphens

In [30]:
similarity(df, mydf, 'nb_hyphens')

Number of matching rows= 11430
Similarity percentage= 100.0

In [31]:
nb_at=[]
for i in mydf['url']:
    nb_at.append(at(i))
mydf['nb_at']=nb_at

In [32]:
similarity(df, mydf, 'nb_at')

Number of matching rows= 11430
Similarity percentage= 100.0

In [33]:
mydf

,url,length_url,length_hostname,nb_dots,nb_hyphens,nb_at
0,http://www.crestonwood.com/router.php,37,19,3,0,0
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1,0,0
2,https://support-appleld.com.secureupdate.duila...,126,50,4,1,0
3,http://rgipt.ac.in,18,11,2,0,0
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15,2,2,0
...,...,...,...,...,...,...
11425,http://www.fontspace.com/category/blackletter,45,17,2,0,0
11426,http://www.budgetbots.com/server.php/Server%20...,84,18,5,0,1
11427,https://www.facebook.com/Interactive-Televisio...,105,16,2,6,0
11428,http://www.mypublicdomainpictures.com/,38,30,2,0,0
11429,http://174.139.46.123/ap/signin?openid.pape.ma...,477,14,24,0,1

In [34]:
nb_qm=[]
for i in mydf['url']:
    nb_qm.append(qm(i))
mydf['nb_qm']=nb_qm

In [35]:
similarity(df, mydf, 'nb_qm')

Number of matching rows= 11430
Similarity percentage= 100.0

In [36]:
mydf

,url,length_url,length_hostname,nb_dots,nb_hyphens,nb_at,nb_qm
0,http://www.crestonwood.com/router.php,37,19,3,0,0,0
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1,0,0,0
2,https://support-appleld.com.secureupdate.duila...,126,50,4,1,0,1
3,http://rgipt.ac.in,18,11,2,0,0,0
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15,2,2,0,0
...,...,...,...,...,...,...,...
11425,http://www.fontspace.com/category/blackletter,45,17,2,0,0,0
11426,http://www.budgetbots.com/server.php/Server%20...,84,18,5,0,1,1
11427,https://www.facebook.com/Interactive-Televisio...,105,16,2,6,0,1
11428,http://www.mypublicdomainpictures.com/,38,30,2,0,0,0
11429,http://174.139.46.123/ap/signin?openid.pape.ma...,477,14,24,0,1,1

In [37]:
nb_and=[]
for i in mydf['url']:
    nb_and.append(countand(i))
mydf['nb_and']=nb_and

In [38]:
similarity(df, mydf, 'nb_and')

Number of matching rows= 11430
Similarity percentage= 100.0

In [39]:
nb_or=[]
for i in mydf['url']:
    nb_or.append(countor(i))
mydf['nb_or']=nb_or

In [40]:
similarity(df, mydf, 'nb_or')

Number of matching rows= 11430
Similarity percentage= 100.0

In [41]:
mydf

,url,length_url,length_hostname,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or
0,http://www.crestonwood.com/router.php,37,19,3,0,0,0,0,0
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1,0,0,0,0,0
2,https://support-appleld.com.secureupdate.duila...,126,50,4,1,0,1,2,0
3,http://rgipt.ac.in,18,11,2,0,0,0,0,0
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15,2,2,0,0,0,0
...,...,...,...,...,...,...,...,...,...
11425,http://www.fontspace.com/category/blackletter,45,17,2,0,0,0,0,0
11426,http://www.budgetbots.com/server.php/Server%20...,84,18,5,0,1,1,0,0
11427,https://www.facebook.com/Interactive-Televisio...,105,16,2,6,0,1,0,0
11428,http://www.mypublicdomainpictures.com/,38,30,2,0,0,0,0,0
11429,http://174.139.46.123/ap/signin?openid.pape.ma...,477,14,24,0,1,1,9,0

In [42]:
nb_eq=[]
for i in mydf['url']:
    nb_eq.append(eq(i))
mydf['nb_eq']=nb_eq

In [43]:
similarity(df, mydf, 'nb_eq')

Number of matching rows= 11430
Similarity percentage= 100.0

In [44]:
nb_underscore=[]
for i in mydf['url']:
    nb_underscore.append(us(i))
mydf['nb_underscore']=nb_underscore

In [45]:
similarity(df, mydf, 'nb_underscore')

Number of matching rows= 11430
Similarity percentage= 100.0

In [46]:
nb_tilde=[]
for i in mydf['url']:
    nb_tilde.append(tilde(i))
mydf['nb_tilde']=nb_tilde

In [47]:
similarity(df, mydf, 'nb_tilde')

Number of matching rows= 11428
Similarity percentage= 99.9825021872266

In [48]:
nb_percent=[]
for i in mydf['url']:
    nb_percent.append(percent(i))
mydf['nb_percent']=nb_percent

In [49]:
similarity(df, mydf, 'nb_percent')

Number of matching rows= 11430
Similarity percentage= 100.0

In [50]:
mydf

,url,length_url,length_hostname,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,nb_eq,nb_underscore,nb_tilde,nb_percent
0,http://www.crestonwood.com/router.php,37,19,3,0,0,0,0,0,0,0,0,0
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1,0,0,0,0,0,0,0,0,0
2,https://support-appleld.com.secureupdate.duila...,126,50,4,1,0,1,2,0,3,2,0,0
3,http://rgipt.ac.in,18,11,2,0,0,0,0,0,0,0,0,0
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15,2,2,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11425,http://www.fontspace.com/category/blackletter,45,17,2,0,0,0,0,0,0,0,0,0
11426,http://www.budgetbots.com/server.php/Server%20...,84,18,5,0,1,1,0,0,1,0,0,1
11427,https://www.facebook.com/Interactive-Televisio...,105,16,2,6,0,1,0,0,1,1,0,0
11428,http://www.mypublicdomainpictures.com/,38,30,2,0,0,0,0,0,0,0,0,0
11429,http://174.139.46.123/ap/signin?openid.pape.ma...,477,14,24,0,1,1,9,0,9,18,0,23

In [51]:
nb_slash=[]
for i in mydf['url']:
    nb_slash.append(slash(i))
mydf['nb_slash']=nb_slash

In [52]:
similarity(df, mydf, 'nb_slash')

Number of matching rows= 11430
Similarity percentage= 100.0

In [53]:
nb_star=[]
for i in mydf['url']:
    nb_star.append(star(i))
mydf['nb_star']=nb_star

In [54]:
similarity(df, mydf, 'nb_star')

Number of matching rows= 11430
Similarity percentage= 100.0

In [55]:
nb_colon=[]
for i in mydf['url']:
    nb_colon.append(colon(i))
mydf['nb_colon']=nb_colon
similarity(df, mydf, 'nb_colon')

Number of matching rows= 11430
Similarity percentage= 100.0

In [56]:
nb_comma=[]
for i in mydf['url']:
    nb_comma.append(comma(i))
mydf['nb_comma']=nb_comma
similarity(df, mydf, 'nb_comma')

Number of matching rows= 11430
Similarity percentage= 100.0

In [57]:
nb_semicolumn=[]
for i in mydf['url']:
    nb_semicolumn.append(semicolumn(i))
mydf['nb_semicolumn']=nb_semicolumn
similarity(df, mydf, 'nb_semicolumn')

Number of matching rows= 11430
Similarity percentage= 100.0

In [58]:
nb_dollar=[]
for i in mydf['url']:
    nb_dollar.append(dollar(i))
mydf['nb_dollar']=nb_dollar
similarity(df, mydf, 'nb_dollar')

Number of matching rows= 11430
Similarity percentage= 100.0

In [59]:
nb_space=[]
for i in mydf['url']:
    nb_space.append(space(i))
mydf['nb_space']=nb_space
similarity(df, mydf, 'nb_space')

Number of matching rows= 11221
Similarity percentage= 98.17147856517936

In [60]:
mydf

,url,length_url,length_hostname,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,nb_eq,nb_underscore,nb_tilde,nb_percent,nb_slash,nb_star,nb_colon,nb_comma,nb_semicolumn,nb_dollar,nb_space
0,http://www.crestonwood.com/router.php,37,19,3,0,0,0,0,0,0,0,0,0,3,0,1,0,0,0,0
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1,0,0,0,0,0,0,0,0,0,5,0,1,0,0,0,0
2,https://support-appleld.com.secureupdate.duila...,126,50,4,1,0,1,2,0,3,2,0,0,5,0,1,0,0,0,0
3,http://rgipt.ac.in,18,11,2,0,0,0,0,0,0,0,0,0,2,0,1,0,0,0,0
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15,2,2,0,0,0,0,0,0,0,0,5,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11425,http://www.fontspace.com/category/blackletter,45,17,2,0,0,0,0,0,0,0,0,0,4,0,1,0,0,0,0
11426,http://www.budgetbots.com/server.php/Server%20...,84,18,5,0,1,1,0,0,1,0,0,1,5,0,1,0,0,0,0
11427,https://www.facebook.com/Interactive-Televisio...,105,16,2,6,0,1,0,0,1,1,0,0,5,0,1,0,0,0,0
11428,http://www.mypublicdomainpictures.com/,38,30,2,0,0,0,0,0,0,0,0,0,3,0,1,0,0,0,0
11429,http://174.139.46.123/ap/signin?openid.pape.ma...,477,14,24,0,1,1,9,0,9,18,0,23,4,0,1,0,9,0,0

In [61]:
nb_www=[]
for i in mydf['url']:
    nb_www.append(www(i))
mydf['nb_www']=nb_www
similarity(df, mydf, 'nb_www')

Number of matching rows= 11428
Similarity percentage= 99.9825021872266

In [62]:
mydf

,url,length_url,length_hostname,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,nb_eq,...,nb_tilde,nb_percent,nb_slash,nb_star,nb_colon,nb_comma,nb_semicolumn,nb_dollar,nb_space,nb_www
0,http://www.crestonwood.com/router.php,37,19,3,0,0,0,0,0,0,...,0,0,3,0,1,0,0,0,0,1
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1,0,0,0,0,0,0,...,0,0,5,0,1,0,0,0,0,0
2,https://support-appleld.com.secureupdate.duila...,126,50,4,1,0,1,2,0,3,...,0,0,5,0,1,0,0,0,0,0
3,http://rgipt.ac.in,18,11,2,0,0,0,0,0,0,...,0,0,2,0,1,0,0,0,0,0
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15,2,2,0,0,0,0,0,...,0,0,5,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11425,http://www.fontspace.com/category/blackletter,45,17,2,0,0,0,0,0,0,...,0,0,4,0,1,0,0,0,0,1
11426,http://www.budgetbots.com/server.php/Server%20...,84,18,5,0,1,1,0,0,1,...,0,1,5,0,1,0,0,0,0,1
11427,https://www.facebook.com/Interactive-Televisio...,105,16,2,6,0,1,0,0,1,...,0,0,5,0,1,0,0,0,0,1
11428,http://www.mypublicdomainpictures.com/,38,30,2,0,0,0,0,0,0,...,0,0,3,0,1,0,0,0,0,1
11429,http://174.139.46.123/ap/signin?openid.pape.ma...,477,14,24,0,1,1,9,0,9,...,0,23,4,0,1,0,9,0,0,1

In [63]:
nb_com=[]
for i in mydf['url']:
    nb_com.append(com(i))
mydf['nb_com']=nb_com
similarity(df, mydf, 'nb_com')

Number of matching rows= 4059
Similarity percentage= 35.511811023622045

In [64]:
nb_dslash=[]
for i in mydf['url']:
    nb_dslash.append(dslash(i))
mydf['nb_dslash']=nb_dslash
similarity(df, mydf, 'nb_dslash')

Number of matching rows= 11430
Similarity percentage= 100.0

In [65]:
http_in_path=[]
for i in mydf['url']:
    http_in_path.append(http_path(i))
mydf['http_in_path']=http_in_path
similarity(df, mydf, 'http_in_path')

Number of matching rows= 11415
Similarity percentage= 99.86876640419948

In [66]:
https_token=[]
for i in mydf['url']:
    https_token.append(https_tok(i))
mydf['https_token']=https_token
similarity(df, mydf, 'https_token')

Number of matching rows= 11380
Similarity percentage= 99.56255468066492

In [67]:
ratio_digits_url=[]
j=-1
for i in mydf['url']:
    j+=1
    ratio_digits_url.append(digits(i)/mydf['length_url'][j])
mydf['ratio_digits_url']=ratio_digits_url
similarity_diff(df, mydf, 'ratio_digits_url')

Number of matching rows= 11424
Similarity percentage= 99.94750656167979

In [68]:
mydf

,url,length_url,length_hostname,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,nb_eq,...,nb_comma,nb_semicolumn,nb_dollar,nb_space,nb_www,nb_com,nb_dslash,http_in_path,https_token,ratio_digits_url
0,http://www.crestonwood.com/router.php,37,19,3,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,1,0.000000
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0.220779
2,https://support-appleld.com.secureupdate.duila...,126,50,4,1,0,1,2,0,3,...,0,0,0,0,0,2,0,0,0,0.150794
3,http://rgipt.ac.in,18,11,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0.000000
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15,2,2,0,0,0,0,0,...,0,0,0,0,1,1,0,0,1,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11425,http://www.fontspace.com/category/blackletter,45,17,2,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,1,0.000000
11426,http://www.budgetbots.com/server.php/Server%20...,84,18,5,0,1,1,0,0,1,...,0,0,0,0,1,2,0,0,1,0.023810
11427,https://www.facebook.com/Interactive-Televisio...,105,16,2,6,0,1,0,0,1,...,0,0,0,0,1,1,0,0,0,0.142857
11428,http://www.mypublicdomainpictures.com/,38,30,2,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,1,0.000000
11429,http://174.139.46.123/ap/signin?openid.pape.ma...,477,14,24,0,1,1,9,0,9,...,0,9,0,0,1,0,0,4,0,0.085954

In [69]:
ratio_digits_host=[]
j=-1
for i in mydf['url']:
    j+=1
    ratio_digits_host.append(digits(i)/mydf['length_hostname'][j])
mydf['ratio_digits_host']=ratio_digits_host
similarity_diff(df, mydf, 'ratio_digits_host')

Number of matching rows= 7638
Similarity percentage= 66.8241469816273

In [70]:
punycode=[]
for i in mydf['url']:
    punycode.append(puny(i))
mydf['punycode']=punycode
similarity(df, mydf, 'punycode')

Number of matching rows= 11385
Similarity percentage= 99.60629921259843

In [71]:
port=[]
for i in mydf['url']:
    port.append(contains_port(i))
mydf['port']=port
similarity(df, mydf, 'port')

Number of matching rows= 11260
Similarity percentage= 98.51268591426071

In [72]:
nb_subdomains=[]
for i in mydf['url']:
    nb_subdomains.append(subdomains(i))
mydf['nb_subdomains']=nb_subdomains
similarity(df, mydf, 'nb_subdomains')

Number of matching rows= 9910
Similarity percentage= 86.70166229221347

In [73]:
# Class 1 represents Phishing, 0 Legit
status=[]
for i in df['status']:
    if i=='phishing':
        status.append(1)
    else:
        status.append(0)
        
mydf['status']=status

In [74]:
mydf

,url,length_url,length_hostname,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,nb_eq,...,nb_com,nb_dslash,http_in_path,https_token,ratio_digits_url,ratio_digits_host,punycode,port,nb_subdomains,status
0,http://www.crestonwood.com/router.php,37,19,3,0,0,0,0,0,0,...,1,0,0,1,0.000000,0.000000,0,0,3,0
1,http://shadetreetechnology.com/V4/validation/a...,77,23,1,0,0,0,0,0,0,...,1,0,0,1,0.220779,0.739130,0,0,1,1
2,https://support-appleld.com.secureupdate.duila...,126,50,4,1,0,1,2,0,3,...,2,0,0,0,0.150794,0.380000,0,0,4,1
3,http://rgipt.ac.in,18,11,2,0,0,0,0,0,0,...,0,0,0,1,0.000000,0.000000,0,0,2,0
4,http://www.iracing.com/tracks/gateway-motorspo...,55,15,2,2,0,0,0,0,0,...,1,0,0,1,0.000000,0.000000,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11425,http://www.fontspace.com/category/blackletter,45,17,2,0,0,0,0,0,0,...,1,0,0,1,0.000000,0.000000,0,0,2,0
11426,http://www.budgetbots.com/server.php/Server%20...,84,18,5,0,1,1,0,0,1,...,2,0,0,1,0.023810,0.111111,0,0,5,1
11427,https://www.facebook.com/Interactive-Televisio...,105,16,2,6,0,1,0,0,1,...,1,0,0,0,0.142857,0.937500,0,0,2,0
11428,http://www.mypublicdomainpictures.com/,38,30,2,0,0,0,0,0,0,...,1,0,0,1,0.000000,0.000000,0,0,2,0
11429,http://174.139.46.123/ap/signin?openid.pape.ma...,477,14,24,0,1,1,9,0,9,...,0,0,4,0,0.085954,2.928571,0,0,24,1

In [75]:
mydf.to_csv('mycsv.csv', index=False)

In [75]:
import matplotlib.pyplot as plt

In [76]:
from sklearn.model_selection import train_test_split

In [98]:
from sklearn import metrics

In [79]:
y=pd.DataFrame(mydf['status'], columns=['status'])

In [80]:
y

       status
0           0
1           1
2           1
3           0
4           0
...       ...
11425       0
11426       1
11427       0
11428       0
11429       1

[11430 rows x 1 columns]

In [81]:
x=mydf

In [82]:
x= x.drop(['status', 'url'],1)

/var/folders/8n/85r5xr6d5s13wgrnpmj4lszc0000gn/T/ipykernel_45292/1835674921.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x= x.drop(['status', 'url'],1)

In [83]:
x

,length_url,length_hostname,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,nb_eq,nb_underscore,...,nb_www,nb_com,nb_dslash,http_in_path,https_token,ratio_digits_url,ratio_digits_host,punycode,port,nb_subdomains
0,37,19,3,0,0,0,0,0,0,0,...,1,1,0,0,1,0.000000,0.000000,0,0,3
1,77,23,1,0,0,0,0,0,0,0,...,0,1,0,0,1,0.220779,0.739130,0,0,1
2,126,50,4,1,0,1,2,0,3,2,...,0,2,0,0,0,0.150794,0.380000,0,0,4
3,18,11,2,0,0,0,0,0,0,0,...,0,0,0,0,1,0.000000,0.000000,0,0,2
4,55,15,2,2,0,0,0,0,0,0,...,1,1,0,0,1,0.000000,0.000000,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11425,45,17,2,0,0,0,0,0,0,0,...,1,1,0,0,1,0.000000,0.000000,0,0,2
11426,84,18,5,0,1,1,0,0,1,0,...,1,2,0,0,1,0.023810,0.111111,0,0,5
11427,105,16,2,6,0,1,0,0,1,1,...,1,1,0,0,0,0.142857,0.937500,0,0,2
11428,38,30,2,0,0,0,0,0,0,0,...,1,1,0,0,1,0.000000,0.000000,0,0,2
11429,477,14,24,0,1,1,9,0,9,18,...,1,0,0,4,0,0.085954,2.928571,0,0,24

In [84]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.15)

In [86]:
from sklearn.neighbors import KNeighborsClassifier

In [94]:
ytrain=ytrain['status'].tolist()

In [111]:
for i in range(2,9):
    neigh = KNeighborsClassifier(n_neighbors=i)
    neigh.fit(xtrain, ytrain)
    y_pred = neigh.predict(xtest)
    accuracy = metrics.accuracy_score(ytest, y_pred)
    print(f"At K= {i}, Accuracy= {accuracy*100} ")

At K= 2, Accuracy= 79.41690962099125
At K= 3, Accuracy= 82.15743440233237
At K= 4, Accuracy= 80.34985422740525
At K= 5, Accuracy= 81.865889212828
At K= 6, Accuracy= 81.04956268221575
At K= 7, Accuracy= 81.45772594752187
At K= 8, Accuracy= 80.466472303207

In [115]:
from concurrent.futures import ProcessPoolExecutor
from concurrent.futures import as_completed
import sklearn.feature_extraction as fe

import datetime
from urllib.parse import urlparse
from tld import get_tld
from cymruwhois import Client
import advertools as adv
import socket
import whois
import time
import dns.resolver
import re
import os

In [116]:
def get_tld_length(str):
    domain = urlparse(str).netloc
    if not url_domain_is_ip(domain):
        tld = get_tld(str, fail_silently=True)
        tld_l = len(tld) if tld else 0
    else:
        tld_l = 0
    return tld_l

def url_domain_is_ip(domain):
    pattern = re.compile("^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$")
    match = pattern.match(domain)
    return int(match is not None)

def is_server_client_domain(domain):
    return int('server' in domain.lower() or 'client' in domain.lower())

def no_of_vowels(domain):
    count = 0
    vowels = set('aeiou')
    for alph in domain.lower():
        if alph in vowels:
            count += 1
    return count

def no_of_parameters(parameter):
    return 0 if parameter == ' ' else len(parameter.split('&'))

def is_tld_in_parameters(parameter):
    tld = get_tld(parameter, fail_silently=True)
    return int(tld is not None)

def domain_loolup_time(domain):
    try:
        dns_start = time.time()
        ip = socket.gethostbyname(domain)
        dns_end = time.time()
        d_time = (dns_end - dns_start) * 1000
    except:
        d_time = -1
    return d_time


def has_domain_spf(domain):
    try:
        result = dns.resolver.resolve(domain, 'TXT')
    except:
        result = None
    return int(result is not None)

def no_of_ip_resolved(domain):
    try:
        result = dns.resolver.resolve(domain, 'A')
    except:
        result = []
    return len(result)

def no_of_mx_servers(domain):
    try:
        result = dns.resolver.resolve(domain, 'MX')
    except:
        result = []
    return len(result)

def no_of_ns_servers(domain):
    try:
        result = dns.resolver.resolve(domain, 'NS')
    except:
        result = []
    return len(result)

def google_index(query):
    cx = '924df684022d64ec3'
    key = 'AIzaSyDyd0ixy47mX4TStwrA93gyu1J9NXxB288'
    p = f'site:{query}'
    search = adv.serp_goog(p,cx,key)
    return int(search.loc[0,'formattedTotalResults'] != '0')

g_index=[]
for i in url:
    g_index.append(google_index(i))
mydf['g_index']=g_index

In [117]:
ns_server=[]
for i in url:
    ns_server.append(no_of_ns_servers(i))
mydf['ns_server']=ns_server

In [ ]:
mx_server=[]
for i in url:
    mx_server.append(no_of_mx_servers(i))
mydf['mx_server']=mx_server

In [ ]:
number_ip_resolved=[]
for i in url:
    number_ip_resolved.append(no_of_ip_resolved(i))
mydf['number_ip_resolved']=number_ip_resolved

In [ ]:
tld_length=[]
for i in url:
    tld_length.append(get_tld_length(i))
mydf['tld_length']=tld_length

In [ ]:
server_client_domain=[]
for i in url:
    server_client_domain.append(is_server_client_domain(i))
mydf['server_client_domain']=server_client_domain

In [ ]:
vowels=[]
for i in url:
    vowels.append(no_of_vowels(i))
mydf['vowels']=vowels

In [ ]:
parameters=[]
for i in url:
    parameters.append(no_of_parameters(i))
mydf['parameters']=parameters

In [ ]:
tld_in_parameters=[]
for i in url:
    tld_in_parameters.append(is_tld_in_parameters(i))
mydf['tld_in_parameters']=tld_in_parameters

In [ ]:
domain_lookup_time=[]
for i in url:
    domain_lookup_time.append(domain_loolup_time(i))
mydf['domain_lookup_time']=domain_lookup_time

In [ ]:
mydf

In [ ]:
def get_domain_url_features(domain):
    result = {'qty_dot_domain': get_no_of_dot(domain),
              'qty_hyphen_domain': get_no_of_hyphen(domain),
              'qty_underline_domain': get_no_of_underline(domain),
              'qty_slash_domain': get_no_of_slash(domain),
              'qty_questionmark_domain': get_no_of_questionmark(domain),
              'qty_equal_domain': get_no_of_equal(domain),
              'qty_at_domain': get_no_of_at(domain),
              'qty_and_domain': get_no_of_and(domain),
              'qty_exclamation_domain': get_no_of_exclamation(domain),
              'qty_space_domain': get_no_of_space(domain),
              'qty_tilde_domain': get_no_of_tilde(domain),
              'qty_comma_domain': get_no_of_comma(domain),
              'qty_plus_domain': get_no_of_plus(domain),
              'qty_asterisk_domain': get_no_of_asterisk(domain),
              'qty_hashtag_domain': get_no_of_hashtag(domain),
              'qty_dollar_domain': get_no_of_dollar(domain),
              'qty_percent_domain': get_no_of_percent(domain),
              'qty_vowels_domain': no_of_vowels(domain),
              'domain_length': get_length(domain),
              'domain_in_ip': url_domain_is_ip(domain),
              'server_client_domain': is_server_client_domain(domain)}
    return result

def get_url_directory_features(directory):
    result = {'qty_dot_directory': get_no_of_dot(directory),
              'qty_hyphen_directory': get_no_of_hyphen(directory),
              'qty_underline_directory': get_no_of_underline(directory),
              'qty_slash_directory': get_no_of_slash(directory),
              'qty_questionmark_directory': get_no_of_questionmark(directory),
              'qty_equal_directory': get_no_of_equal(directory),
              'qty_at_directory': get_no_of_at(directory),
              'qty_and_directory': get_no_of_and(directory),
              'qty_exclamation_directory': get_no_of_exclamation(directory),
              'qty_space_directory': get_no_of_space(directory),
              'qty_tilde_directory': get_no_of_tilde(directory),
              'qty_comma_directory': get_no_of_comma(directory),
              'qty_plus_directory': get_no_of_plus(directory),
              'qty_asterisk_directory': get_no_of_asterisk(directory),
              'qty_hashtag_directory': get_no_of_hashtag(directory),
              'qty_dollar_directory': get_no_of_dollar(directory),
              'qty_percent_directory': get_no_of_percent(directory),
              'directory_length': get_length(directory)}
    return result

def get_url_file_features(file_name):
    result = {'qty_dot_file': get_no_of_dot(file_name),
              'qty_hyphen_file': get_no_of_hyphen(file_name),
              'qty_underline_file': get_no_of_underline(file_name),
              'qty_slash_file': get_no_of_slash(file_name),
              'qty_questionmark_file': get_no_of_questionmark(file_name),
              'qty_equal_file': get_no_of_equal(file_name),
              'qty_at_file': get_no_of_at(file_name),
              'qty_and_file': get_no_of_and(file_name),
              'qty_exclamation_file': get_no_of_exclamation(file_name),
              'qty_space_file': get_no_of_space(file_name),
              'qty_tilde_file': get_no_of_tilde(file_name),
              'qty_comma_file': get_no_of_comma(file_name),
              'qty_plus_file': get_no_of_plus(file_name),
              'qty_asterisk_file': get_no_of_asterisk(file_name),
              'qty_hashtag_file': get_no_of_hashtag(file_name),
              'qty_dollar_file': get_no_of_dollar(file_name),
              'qty_percent_file': get_no_of_percent(file_name),
              'file_length': get_length(file_name)}
    return result

def get_url_parameter_features(parameter):
    result = {'qty_dot_params': get_no_of_dot(parameter),
              'qty_hyphen_params': get_no_of_hyphen(parameter),
              'qty_underline_params': get_no_of_underline(parameter),
              'qty_slash_params': get_no_of_slash(parameter),
              'qty_questionmark_params': get_no_of_questionmark(parameter),
              'qty_equal_params': get_no_of_equal(parameter),
              'qty_at_params': get_no_of_at(parameter),
              'qty_and_params': get_no_of_and(parameter),
              'qty_exclamation_params': get_no_of_exclamation(parameter),
              'qty_space_params': get_no_of_space(parameter),
              'qty_tilde_params': get_no_of_tilde(parameter),
              'qty_comma_params': get_no_of_comma(parameter),
              'qty_plus_params': get_no_of_plus(parameter),
              'qty_asterisk_params': get_no_of_asterisk(parameter),
              'qty_hashtag_params': get_no_of_hashtag(parameter),
              'qty_dollar_params': get_no_of_dollar(parameter),
              'qty_percent_params': get_no_of_percent(parameter),
              'params_length': get_length(parameter),
              'tld_present_params': is_tld_in_parameters(parameter),
              'qty_params': no_of_parameters(parameter)}
    return result

def get_ex_services_features(url):
    domain = urlparse(url).netloc
    result = {'time_response': domain_loolup_time(domain),
              'domain_spf': has_domain_spf(domain),
              'asn_ip': asn_ip(domain),
              'qty_ip_resolved': no_of_ip_resolved(domain),
              'qty_nameservers': no_of_ns_servers(domain),
              'qty_mx_servers': no_of_mx_servers(domain),
              'qty_redirects': no_of_redirection(url)}
              # 'url_google_index': google_index(url),
              # 'domain_google_index': google_index(domain)}
    return result

def get_features(url):
    uri = urlparse(url)
    directory = os.path.dirname(uri.path)
    file_name = os.path.basename(uri.path)
    url_features = get_url_features(url)
    domain_features = get_domain_url_features(uri.netloc)
    directory_features = get_url_directory_features(directory)
    file_features = get_url_file_features(file_name)
    parameter_features = get_url_parameter_features(uri.query)
    externel_features = get_ex_services_features(url)
    features = {**url_features, **domain_features, **directory_features, **file_features,
                **parameter_features, **externel_features}
    return features

In [ ]:
mydf